### ISSUE TITLE
No Test Found 

### ISSUE THREAD

**Issue by gtodd876** [microsoft/playwright-vscode#120]
* Using Windows 10
* Install Microsoft's official Playwright extension
* Add Playwright to project with `Ctrl-Shift-P` and typing `install playwright`
* Click on the `Testing` Icon on the Activity bar to open Playwright extension pane
* No tests are found
* No green play buttons to run isolated tests in the test file 
![image](https://user-images.githubusercontent.com/28220658/155334438-5ac567fb-35bf-4b04-8244-cd7b7ab3d4f2.png)

**Comment by alexneo2003** [comment]
have same issue
playwright extention v0.0.9 - have all 
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/11705902/155530217-913076ec-8f16-4508-9003-dc68a2b599f2.png">

v0.2.1 - there is nothing
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/11705902/155531096-35eb3164-222c-4bab-af76-c80a919cd58e.png">

**Comment by mxschmitt** [comment]
@alexneo2003 Which version of `@playwright/test` are you using? having a repro would be helpful to dig into that.

**Comment by alexneo2003** [comment]
> @alexneo2003 Which version of `@playwright/test` are you using? having a repro would be helpful to dig into that.

using latest playwright package (1.19.1)
VSCode - version 1.64
OS - macOS 12.2.1

i'm create sample project
- disable all extentions at VSCode
- install latest playwright extention - 0.2.1
- run `npm init playwright`
with 0.2.1 version - working


at my own project
with 0.0.9 version - working
with 0.2.1 version - not working
sorry but i'm cant make repro

maybe i'm can make some debug with extention - say me how

**Comment by gtodd876** [comment]
![image](https://user-images.githubusercontent.com/28220658/155574186-42228dc9-9b16-42c1-8b56-5995b40788ce.png)
Only enabled extension is playwright test for vs code
![image](https://user-images.githubusercontent.com/28220658/155574285-b5747c00-7d89-4443-8fef-36caa98b8d27.png)
![image](https://user-images.githubusercontent.com/28220658/155574314-a28aa71a-c0af-4ee5-99a8-92b0496a244e.png)
Extension version 0.2.1
use the command pallet to install playwright (currently installs v.1.19.2
![image](https://user-images.githubusercontent.com/28220658/155574529-ed517f37-47e5-4cf9-acd2-323e7fb2ad9c.png)
![image](https://user-images.githubusercontent.com/28220658/155574670-3f630e5a-82de-4e17-b240-bcc0214cdeaa.png)
No green arrows to run isolated tests
![image](https://user-images.githubusercontent.com/28220658/155574798-88b177bd-8900-423d-8ada-866c97fb6e0f.png)

No tests found
![image](https://user-images.githubusercontent.com/28220658/155574859-13ec505d-ea73-474b-91eb-c67db7e30a00.png)

Let me know if this reproduction steps from a blank folder on Windows 10 aren't clear.

**Comment by sergioariveros** [comment]
Same error on this side, additionally we already have installed the playwright test package but looks like the extension dont recognize that and we have to do and install again from vscode

Playwright version: 1.19.1
VSCode - version 1.64
OS - macOS 10.15.7
Playwright extension: 0.2.2

1. Not error found
![Screen Shot 2022-03-02 at 12 09 22 AM](https://user-images.githubusercontent.com/19369277/156299582-ae792bc4-d6bd-4a4f-95ab-394a363176a4.png)

2.  Not extension detected
![Screen Shot 2022-03-02 at 12 16 11 AM](https://user-images.githubusercontent.com/19369277/156300421-ba6f918b-5b6d-4f7b-ae30-7b509cb20064.png)

3. When is installed from Microsoft is getting this error from the terminal:
![Screen Shot 2022-03-02 at 12 17 59 AM](https://user-images.githubusercontent.com/19369277/156300445-21fcb94d-30fe-42bc-8cdc-4cadabc7e870.png)

**Comment by mxschmitt** [comment]
@sergioariveros could you do `npm --version` and `node --version`?

**Comment by sergioariveros** [comment]
Sure, these are the results:
`npm --version = 6.14.13`
`node --version = v14.17.0`

**Comment by pavelfeldman** [comment]
@sergioariveros what is your project folder / file structure?

**Comment by gtodd876** [comment]
I was on Node 14 and thought maybe that could be the issue.
I updated to Node 16  and the extension is still in broken state. Here are my versions
![image](https://user-images.githubusercontent.com/28220658/156444670-6f565bba-9c75-4bce-afea-2de5f9855d0a.png)
The extension still does not work.
![image](https://user-images.githubusercontent.com/28220658/156444762-173cfa6b-b414-4047-82be-883b2c07d996.png)
![image](https://user-images.githubusercontent.com/28220658/156444797-10a6c36a-42e6-4ea1-973c-276cbe254129.png)

I do notice in the about page my VS Code install lists Node v.14 how do I change the VS Code electron app to use Node 16?
![image](https://user-images.githubusercontent.com/28220658/156445096-ef226d2c-6cdc-4e17-8bfb-c7e2ed961c01.png)

**Comment by sergioariveros** [comment]
@pavelfeldman is as follows: 
![Screen Shot 2022-03-02 at 3 38 05 PM](https://user-images.githubusercontent.com/19369277/156446003-d9b5d8a8-461c-49af-bf21-91ca0fdacda3.png)

**Comment by mxschmitt** [comment]
> Sure, these are the results: `npm --version = 6.14.13` `node --version = v14.17.0`

We published a new version which includes better error reporting with matching line numbers.

Could you try executing the following? `npm init playwright@latest -- --quiet --browser=chromium`?

**Comment by sergioariveros** [comment]
Hi, sorry for the delay, same errors:
![Screen Shot 2022-03-08 at 1 06 43 PM](https://user-images.githubusercontent.com/19369277/157299610-1fd8e8a8-c323-4225-8148-af3bb2c913bb.png)

**Comment by mxschmitt** [comment]
@sergioariveros very helpful, thank you! The fix for this one went live a few minutes ago. (It was not compatible with NPM 6).

**Comment by sergioariveros** [comment]
So I tested again, now is not generating that error regarding to the installation, thanks for that!

In the other hand, is still present the other issue, so let me show you what I am seeing now that maybe help you to get some insights, I did the installation and that creates a new `playwright.config.ts` ignoring that i already have `config.ts`, curious thing is that those examples tests that the installation autogenerate `e2e\example.spec.ts` are being recognized but not my tests that I have in `tests` folder
![Screen Shot 2022-03-08 at 2 55 48 PM](https://user-images.githubusercontent.com/19369277/157315706-2d3fd3b3-019e-4b56-a185-73845c6e3ccb.png)

**Comment by sergioariveros** [comment]
Weird, because thats the thing I already have Playwright installed and is not recongnizing my test even when I rename the config file:
![Screen Shot 2022-03-08 at 3 52 03 PM](https://user-images.githubusercontent.com/19369277/157323238-a541c3fb-f220-4547-b19c-653ef29f38ed.png)
![Screen Shot 2022-03-08 at 3 52 29 PM](https://user-images.githubusercontent.com/19369277/157323251-e9e3a746-ab75-4231-8ef8-df86874b274c.png)

But if I do an additional install from VSCode console, automatically recognize the tests:

![Screen Shot 2022-03-08 at 3 55 17 PM](https://user-images.githubusercontent.com/19369277/157323429-fb315662-bc65-4962-8382-d8b0f987ba81.png)

So everytime I enter to VSCode I will have to do the same otherwise is not recognizing the tests

**Comment by laviniaSer07** [comment]
Is this plugin compatible with the test that are written with Gherkin? I added it, but it seems that doesn't support cucumber and doesn't find the tests. Or can it be planned as a feature?

**Comment by vhscom** [comment]
Was seeing this issue until I added `testsDir` to playwright config. Then I removed `testsDir` from my config and restarted VSCode and extension finds tests despite the removal of the `testsDir` key from the config. Under either condition the spec files I have in my test dir are found but the plug-in cannot see nor execute any of the tests inside them.

I'm using a `ts` style playwright config file and `@playwright/test@1.21.1` with Node v17.7.1. I presume the issue has something to do with the experimental loader and transition to ESM. But that's just a hunch. Will try this extension in the future perhaps when some of these wrinkles have been ironed out.

**Comment by vhscom** [comment]
Was seeing this issue until I added `testsDir` to playwright config. Then I removed `testsDir` from my config and restarted VSCode and extension finds test files despite the removal of the `testsDir` key from the config. Under either condition the spec files I have in my test dir are found but the plug-in cannot see nor execute any of the tests inside them.

I'm using a `ts` style playwright config file and `@playwright/test@1.21.1` with Node v17.7.1. I presume the issue has something to do with the experimental loader and transition to ESM. But that's just a hunch. Will try this extension in the future perhaps when some of these wrinkles have been ironed out.

**Comment by RickMeijer** [comment]
I have the same problem now. And it used to work. Not sure what broke it. Tried all the steps in this topic, to no avail.
Playwright itself runs fine, fortunately. But I do miss the ease 'run this one test' button.

**Comment by hare0319** [comment]
I found there's another case, which leads to this No Test Found issue.

When there's some error in the implementation, the plugin simply can't find the test without any message, this could be confused sometimes. Especially, when I try to import libs from some other files, and some exceptions thrown from there.

**Comment by hare0319** [comment]
I found there's another case, which leads to this No Test Found issue.

When there's some error in the implementation, the plugin simply can't find the test without any message, this could be confused sometimes. Especially, when I try to import libs from some other files, and some exceptions thrown from there.

**Comment by wahreChrist** [comment]
I have similar issue on Linux (Ubuntu 20.04 NEON KDE), but in my case Testing Bar acting like I dont have Playwright extension installed, even though its there and it can run "Install Playwright" (v. v0.2.5). I tried to change Node versions with NVM to 12.22.7 and 16.15.1, but to no avail. Tried removing and adding different test folders in config file, like it was discussed in here but it didnt work as well. Does anyone know what might be the issue in here?
![Screenshot_20220629_144130](https://user-images.githubusercontent.com/61061924/176440386-6b244c0f-92f5-4226-8193-8bd44dd820c9.png)

**Comment by jcalfee** [comment]
I think we need some log messages...

**Comment by biswanathroy7** [comment]
I just ran "npm install -D @playwright/test" and the tests showed up for me.

**Comment by icharge** [comment]
My issue, When enable `dotenv` line and save. "No test have been found".
![image](https://user-images.githubusercontent.com/1619007/178927469-00b9851d-0333-4f67-8c6a-b0fef6168ec4.png)

**Comment by bshostak** [comment]
I'm experiencing similar issues as above with VSCode. Tests run via CLI just fine, but the Microsoft Playwright Runner cannot find my tests. I'm using Playwright within another codebase but this has worked in the past before. I have Project folder with it's own package.json and src files. Then within that folder there is a folder housing all my Playwright stuff with it's own package.json to go with it. So like:

-Project
-automation
--tests
--playwright.config.ts
--package.json
--etc
-src
-package.json
-etc

**Comment by abhi1708jain** [comment]
Getting the same error " on Mac with all the latest versions. Test Run via CLI just fine. Any solution ? 
<img width="335" alt="Screen Shot 2022-08-06 at 4 11 40 PM" src="https://user-images.githubusercontent.com/90297365/183268664-9c0f87da-5e34-425d-91c4-0338ad0bff8e.png">

**Comment by SobalYauheniya** [comment]
Hello, 
I have the same issue now.
I can run only if test has **only**
test.describe.only

**Comment by bshostak** [comment]
I just wanted to comment something I did that seemed to help:

I use NVM and I would periodically get an error message that my shell was too slow to start up. When I would see this message I would not see my tests via the Playwright extension. So I added this to my zshrc:
```export NVM_DIR=“$HOME/.nvm”
[[ -s “$NVM_DIR/nvm.sh” ]] && source “$NVM_DIR/nvm.sh” --no-use
#[ -s “$NVM_DIR/nvm.sh” ] && \. “$NVM_DIR/nvm.sh”  # This loads `nvm`
#[ -s “$NVM_DIR/bash_completion” ] && \. “$NVM_DIR/bash_completion”  # This loads nvm bash_completion```


After Mac restart, never saw the error again and my tests constantly show up now. So idk.

**Comment by cat-ninja** [comment]
I have the same situation. The extension is unable to find any tests in my project.
My tests located at <>

Here is my config:
```ts
{
  testDir: "src/tests",
  testMatch: /.*(test)\.(ts)/,
  forbidOnly: !!process.env.CI,
  timeout: 300000,
  workers: 2,
  expect: { timeout: 10000 },
  reporter: [["dot"], ["html", { open: "never" }]],
  globalSetup: "./src/hooks/setup.ts",
  use: {
    headless: true,
    screenshot: "only-on-failure",
    trace: process.env.TRACE ? "on" : "on-first-retry",
    actionTimeout: 10000,
    baseURL: process.env.HOST_FRONTEND,
  },
};
```

**Comment by amalsgit** [comment]
I also face the same issue now. I get this error from vs code, but the package already exists and nothing changes even if I install it again 🤷‍♂️ 
![image](https://user-images.githubusercontent.com/22020329/184640328-51c9fa8e-18f8-45d7-a347-79c9148efd30.png)

Playwright test version: 1.25.0
Extension version: v0.2.8
VS Code version: 1.70.0
Node version: 16.14.2
OS: MacOS 12.5

**Comment by MateoSocha** [comment]
I have the same problem on macOS. Everything is up to date even though the extension returns a message about no tests. I have checked on several different projects and the same thing everywhere. Strangely enough on another Windows computer it works fine. Maybe there is some specific configuration on macOS that causes this?

**Comment by HJordan35** [comment]
Same issue for me on MacOS - However, for a time ~2 months ago, the extension was working fine (and I LOVED it). I unfortunately cannot pinpoint the exact point in time in where the extension stopped working. I tried down-grading a few versions and no luck.

Playwright test version: 1.25.0
Extension version: v0.2.9
VS Code version: 1.70.2
Node version: 16.14.2
OS: MacOS 12.2.1
